# Generated by Django 5.1.5 on 2025-04-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
